name: FlashTags
version: '${project.version}'
main: dev.fumaz.flashtags.FlashTags
api-version: 1.13
authors: [ Fumaz ]
website: https://fumaz.dev
commands:
  tag: { }
  givetag: { }
  createtag: { }
  deletetag: { }